services:
  nexuschat.api:
    image: nexuschat.api
    build:
      context: .
      dockerfile: src/NexusChat.Api/Dockerfile
      target: build
      
    command:
      dotnet watch run --no-hot-reload
    
    container_name: backend_nexuschat
    
    env_file:
      - .env
      
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    networks:
      - nexus-backend
      - nexus-frontend
      
    develop:
      watch:
        - action: sync
          path: ./src
          target: ./src
        
  cache:
    image: redis:8.6.1-alpine
    container_name: data_cache
    volumes:
      - redis_data:/data
    networks:
      - nexus-backend
    command:
      redis-server --requirepass ${REDIS_PASSWORD}
    
networks:
  nexus-backend:
    driver: bridge
  nexus-frontend:
    driver: bridge
    
volumes:
    redis_data:

