services:
  nexuschat.api:
    image: nexuschat.api
    build:
      context: .
      dockerfile: src/NexusChat.Api/Dockerfile
      
    environment:
        - ConnectionStrings__DefaultConnection=${DEFAULT_CONNECTION}
        - Jwt__Key=${JWT_KEY}
        - Jwt__Issuer=${JWT_ISSUER}
        - Jwt__Audience=${JWT_AUDIENCE}
        - Cloudinary__CloudName=${CLOUDINARY_CLOUDNAME}
        - Cloudinary__ApiKey=${CLOUDINARY_APIKEY}
        - Cloudinary__ApiSecret=${CLOUDINARY_APISECRET}
      
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    networks:
      - backend
      - frontend
        
  cache:
    image: redis:8.6.1-alpine
    container_name: data_cache
    ports:
      - "6379:6379"
    networks:
      - backend
    
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
      



